# Generated by Django 4.0.5 on 2022-09-06 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='lat',
            new_name='lat_final',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='lng',
            new_name='lat_inicial',
        ),
        migrations.AddField(
            model_name='pedido',
            name='lng_final',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='lng_inicial',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
